import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CartService } from '../../services/cart.service';

@Component({
  standalone: true,
  selector: 'app-cart-drawer', imports: [RouterLink],
  template: `@if (cart.drawerOpen()) {<div class="drawer-backdrop" (click)="close()"></div>}<aside class="cart-drawer" [class.open]="cart.drawerOpen()" aria-label="Shopping cart"><div class="drawer-head"><h2>Your cart <span>{{cart.count()}}</span></h2><button type="button" aria-label="Close cart" (click)="close()">×</button></div>@if (cart.items().length) {<div class="drawer-items">@for (item of cart.items(); track item.id) {<article><img [src]="item.images[0]" [alt]="item.title"><div><h3>{{item.title}}</h3><p>&#36;{{item.price}}</p><div class="quantity"><button (click)="cart.decrease(item.id)" aria-label="Decrease quantity">−</button><span>{{item.quantity}}</span><button (click)="cart.increase(item.id)" aria-label="Increase quantity">+</button></div><button class="remove" (click)="cart.remove(item.id)">Remove</button></div></article>}</div><div class="drawer-total"><span>Subtotal</span><strong>&#36;{{cart.subtotal().toFixed(2)}}</strong></div><a class="button" routerLink="/cart" (click)="close()">View cart <b>↗</b></a>} @else {<p class="empty">Your cart is waiting for something considered.</p>}</aside>`,
  styles: [`.drawer-backdrop{position:fixed;inset:0;background:rgba(23,33,31,.45);z-index:30}.cart-drawer{position:fixed;z-index:31;right:0;top:0;height:100vh;width:min(430px,100%);background:var(--paper);padding:30px;transform:translateX(100%);transition:transform .25s ease;box-shadow:-10px 0 30px #17211f15}.cart-drawer.open{transform:translateX(0)}.drawer-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:18px}.drawer-head h2{font:500 28px 'Space Grotesk';margin:0}.drawer-head h2 span{font:11px 'DM Mono';color:var(--muted)}.drawer-head button{background:transparent;border:0;font-size:28px;cursor:pointer}.drawer-items{overflow:auto;max-height:calc(100vh - 230px)}article{display:grid;grid-template-columns:92px 1fr;gap:16px;padding:22px 0;border-bottom:1px solid var(--line)}article img{width:92px;height:110px;object-fit:cover}h3{font:500 16px 'Space Grotesk';margin:0 0 8px}article p{font-size:13px;margin:0 0 14px}.quantity{display:flex;align-items:center;gap:14px}.quantity button{width:24px;height:24px;border:1px solid var(--line);background:transparent;cursor:pointer}.quantity span{font-size:12px}.remove{border:0;background:transparent;padding:12px 0 0;text-decoration:underline;font-size:10px;cursor:pointer;color:var(--muted)}.drawer-total{display:flex;justify-content:space-between;padding:24px 0;font-size:13px}.drawer-total strong{font:500 18px 'Space Grotesk'}.cart-drawer>.button{display:block;text-align:center}.empty{color:var(--muted);font-size:13px;margin-top:40px}`],
})
export class CartDrawerComponent { cart = inject(CartService); close() { this.cart.closeDrawer(); } }

