import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CartService } from '../../services/cart.service';
@Component({
  standalone: true,
  imports: [RouterLink],
  template: `<section class="cart-page"><p class="eyebrow">Northstar shop</p><h1>Your cart <span>{{cart.count()}}</span></h1>@if (cart.items().length) {<div class="cart-layout"><div>@for (item of cart.items(); track item.id) {<article><img [src]="item.images[0]" [alt]="item.title"><div class="item-info"><a [routerLink]="['/product', item.id]"><h2>{{item.title}}</h2></a><p>&#36;{{item.price.toFixed(2)}}</p><div class="quantity"><button (click)="cart.decrease(item.id)">−</button><span>{{item.quantity}}</span><button (click)="cart.increase(item.id)">+</button></div></div><div class="item-total">&#36;{{(item.price * item.quantity).toFixed(2)}}<button (click)="cart.remove(item.id)">Remove</button></div></article>}</div><aside><h2>Summary</h2><p><span>Subtotal</span><strong>&#36;{{cart.subtotal().toFixed(2)}}</strong></p><p><span>Shipping</span><strong>Calculated at checkout</strong></p><hr><p><span>Total</span><strong>&#36;{{cart.subtotal().toFixed(2)}}</strong></p><button class="button" disabled>Checkout coming soon <b>↗</b></button></aside></div>} @else {<div class="empty-cart"><p>Your cart is waiting for something considered.</p><a class="button" routerLink="/">Continue shopping <b>↗</b></a></div>}</section>`,
  styles: [`.cart-page{max-width:var(--max);margin:auto;padding:90px 5vw 130px}.cart-page h1{font:500 76px 'Space Grotesk';letter-spacing:-.07em;margin:20px 0 65px}.cart-page h1 span{font:12px 'DM Mono';color:var(--muted);vertical-align:top;letter-spacing:0}.cart-layout{display:grid;grid-template-columns:2fr 1fr;gap:10%}.cart-layout article{display:grid;grid-template-columns:130px 1fr auto;gap:25px;border-top:1px solid var(--line);padding:25px 0}.cart-layout article img{width:130px;height:155px;object-fit:cover}.item-info h2{font:500 22px 'Space Grotesk';margin:0 0 8px}.item-info p{font-size:13px}.quantity{display:flex;align-items:center;border:1px solid var(--line);width:max-content;margin-top:35px}.quantity button{width:32px;height:32px;border:0;background:transparent;cursor:pointer;font-size:18px}.quantity span{width:24px;text-align:center;font-size:12px}.item-total{font:500 16px 'Space Grotesk';text-align:right}.item-total button{display:block;border:0;background:transparent;text-decoration:underline;color:var(--muted);font-size:10px;cursor:pointer;margin-top:12px}aside{background:#e0e1d7;padding:28px;height:max-content}aside h2{font:500 25px 'Space Grotesk';margin:0 0 30px}aside p{display:flex;justify-content:space-between;font-size:12px;color:var(--muted)}aside p strong{color:var(--ink);font-weight:500}aside hr{border:0;border-top:1px solid var(--line);margin:24px 0}.empty-cart{border-top:1px solid var(--line);padding-top:35px}.empty-cart p{color:var(--muted);font-size:14px}@media(max-width:700px){.cart-page{padding:65px 7vw}.cart-page h1{font-size:57px;margin-bottom:45px}.cart-layout{display:block}.cart-layout article{grid-template-columns:85px 1fr auto;gap:14px}.cart-layout article img{width:85px;height:110px}.item-info h2{font-size:17px}.quantity{margin-top:20px}aside{margin-top:55px}.item-total{font-size:13px}}`],
})
export class CartPage { readonly cart = inject(CartService); }


